sources:
  - Sepehr-Thin.glyphs
  - Sepehr-Light.glyphs
  - Sepehr-Regular.glyphs
  - Sepehr-Medium.glyphs
  - Sepehr-Bold.glyphs

familyName: "Sepehr"

buildOTF: false
buildVariable: true
outputDir: "../fonts"
buildVariable: true
outputDir: "../fonts"

stat:
  Sepehr[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: Bold
      value: 700
