sources:
  - Sepehr-Thin.glyphs
  - Sepehr-Light.glyphs
  - Sepehr-Regular.glyphs
  - Sepehr-Medium.glyphs
  - Sepehr-Bold.glyphs

familyName: "Sepehr"

buildOTF: false
buildTTF: true
buildVariable: false
outputDir: "../fonts"
